### ISSUE TITLE
How to make vector with data?

### ISSUE THREAD

**Issue by Bissiatti** [thenumbernine/lua-gnuplot#1]
Hi, if I use `data = {x,y}` is possible to create a point. But if I pass 4 elements, `data = {x1,y1,x2,y2}` to make a vector (style = 'data vector') return this error:

`"___tmp.gnuplot.cmds.txt" line 4: Not enough columns for this style"`

So, How I draw a vector with lua-gnuplot?

**Comment by thenumbernine** [comment]
Here's an example of drawing with `style = 'data vector'`.  Maybe you forgot to specify all 4 columns in your `using` field of your plot entry?
``` lua
require 'gnuplot'{
	persist = true,
	style = 'data vector',
	data = {
		{0,0,1},
		{0,1,1},
		{.5, -.5, 1},
		{.5, .5, 0},
	},
	{using = '1:2:3:4'},
}
```

**Comment by Bissiatti** [comment]
Thank you, I didn't know I needed to do this. Your lib is good.
