### ISSUE TITLE
How to use splot?

### ISSUE THREAD

**Issue by Bissiatti** [thenumbernine/lua-gnuplot#2]
Hi, I need plot a 3d parametrical curve {sin(u),cos(u),u}, but if I write this:

```lua
local toPlot = {
    "set grid",
    "set parametric",
    {"sin(u),cos(u),u"},
}
gnuplot(toPlot)
```
Not found:

"___tmp.gnuplot.cmds.txt" line 3: undefined variable: u"

I need use splot to gnuplot make a 3d plot, but I don't know how make this with your lib.

**Comment by thenumbernine** [comment]
So yup, you can use each table entry as a separate gnuplot command.
Using that format you can just write
```
gnuplot{
    persist=true,
    "set grid",
    "set parametric",
    "splot sin(u),cos(u),u",
}
```

Or if you would like to use the named-arguments, you can do this:
```
gnuplot{
    persist=true,
    'set grid',
    parametric=true,
    {splot=true, 'sin(u),cos(u),u'},
}
```
...and both will produce this:
![image](https://user-images.githubusercontent.com/4241230/161194883-8425a272-9827-41f6-97cb-d1e5787d40e9.png)

**Comment by Bissiatti** [comment]
Thank you, the last one is better to use.
